Fix issue with `ErmrestAlias._digest_alias_args` expecting `name` and `description` to be passed positionally when they are really optional in all usage patterns. Changed them to kwargs with None defaults.
Fixes:
```
ermrest_catalog.py, line 1256, in update
    rep = self._digest_alias_args(id, owner, alias_target)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ErmrestAlias._digest_alias_args() missing 2 required positional arguments: 'name' and 'description'
```

NOTE: should look at `ErmrestAlias.update` and decide whether it should take `name` and `description` as additional parameters for the update. That seems to be the true problem with this issue, since that behavior is unsupported yet `_digest_alias_args` was expecting them.